TICK = 0.5
SUN_TICKS = 1
COMMON_TICKS = 2

ZOMBIE_CONFIDENCE = 0.6

# Image Config
PLANT_SUNFLOWER = "0.jpg"
PLANT_TWIN_SUNFLOWER = "1.jpg"
PLANT_REPEATER = "2.jpg"
PLANT_PUMPKIN = "3.jpg"
PLANT_SPIKE_WEED = "4.jpg"
PLANT_SPIKE_ROCK = "5.jpg"
PLANT_TORCH_WOOD = "6.jpg"
PLANT_TALL_NUT = "7.jpg"
PLANT_POTATO_MINE = "8.jpg"
PLANT_SQUASH = "9.jpg"

#  Card Index
CARD_SUNFLOWER = 0
CARD_REPEATER = 1
CARD_PUMPKIN = 2
CARD_SPIKE_WEED = 3
CARD_TORCH_WOOD = 4
CARD_TALL_NUT = 5
CARD_POTATO_MINE = 6
CARD_SQUASH = 7
